### ISSUE TITLE
Cannot convert Symfony configuration from yaml to php

### ISSUE THREAD

**Issue by garak** [migrify/migrify#119]
I'd like to convert configuration of packages in a Symfony (5.1) project of mine. Current configurations are in yaml format.
I installed (globally) `migrify/config-transformer` (current installed version: v0.3.17). PHP version is 7.4.3.
I tried to run `~/.composer/bin/config-transformer switch-format config/ -i yaml -o php -s 5.1`

The first run ended with an error due to a configuration of a bundle ("There is no extension able to load the configuration for FooBundle"). I thought it could be acceptable, so I deleted that file.
On secon run, I got following error:

>PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migrify\ConfigTransformer\FormatSwitcher\PhpParser\NodeFactory\ReturnClosureNodesFactory::createFromYamlArray() must be of the type array, null given, called in /home/garak/.composer/vendor/migrify/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php on line 68 and defined in /home/garak/.composer/vendor/migrify/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ReturnClosureNodesFactory.php:43
Stack trace:
#0 /home/garak/.composer/vendor/migrify/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php(68): Migrify\ConfigTransformer\FormatSwitcher\PhpParser\NodeFactory\ReturnClosureNodesFactory->createFromYamlArray()
#1 /home/garak/.composer/vendor/migrify/config-transformer/packages/format-switcher/src/Converter/ConfigFormatConverter.php(81): Migrify\ConfigTransformer\FormatSwitcher\Converter\YamlToPhpConverter->convert()
#2 /home/garak/.composer/vendor/migrify/config-transformer/packages/format-sw in /home/garak/.composer/vendor/migrify/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ReturnClosureNodesFactory.php on line 43

**Comment by TomasVotruba** [comment]
Hi, 

what is the minimal YAML content causing this?

**Comment by garak** [comment]
Hi Tomas, thanks for the quick reply.
Indeed I realized that it was an empty file. My bad, I don't know how I could left that. Anyway, maybe it should be an edge case that should be covered.

Furthermore, after deleting that (empty) file, I'm striking above problem again, this time with a more popular library:

>  There is no extension able to load the configuration for "monolog" (in "/myproj/config/packages/dev/monolog.yaml"). Looked for namespace "monolog", found "none".

**Comment by TomasVotruba** [comment]
Empty files should be skipped, indeed.

For the monolog, extension support is not added yet.
As hot fix, I'd skip it.

As long fix, could you provide minimal input file and expected php output for it? I never worked with PHP defined extensions, so I need some model example.

**Comment by garak** [comment]
Well', I don't know what is the expected php output.
I arrived here from https://twitter.com/rectorphp/status/1286042647598190594 and I thought this could be feasible to use for converting Symfony configuration. But if you still don't support monolog (that is shipped by default with Symfony), I guess it's still not possible.

**Comment by TomasVotruba** [comment]
That makes sense :+1: It's working for Symfony config, but not for Extension configs yet.
You're the first one to report this, it's very fresh package.

**Comment by TomasVotruba** [comment]
Here is relevant source from Symfony:

- https://symfony.com/doc/2.2/cookbook/bundles/extension.html

## Before

![image](https://user-images.githubusercontent.com/924196/88412104-5243e500-cdd9-11ea-8134-e07d57a33650.png)


## After

![image](https://user-images.githubusercontent.com/924196/88412078-49ebaa00-cdd9-11ea-986f-d0c8166419dc.png)

**Comment by TomasVotruba** [comment]
`extension()` method from Symfony for DSL:

https://github.com/symfony/symfony/blob/0ab5eeddf97d0a277c5ad956a51365aba93b27b9/src/Symfony/Component/DependencyInjection/Loader/Configurator/ContainerConfigurator.php#L48-L56

**Comment by garak** [comment]
This is a more up-to-date link: https://symfony.com/doc/master/bundles/configuration.html

**Comment by TomasVotruba** [comment]
Indeed, Google gave me oldie :) updated, thanks!

**Comment by TomasVotruba** [comment]
I'll handle it tonight

**Comment by TomasVotruba** [comment]
Ready for testing in the wild.

Be sure to read #120 description, there are notes about consistency

**Comment by garak** [comment]
Not working for routing/services configuration, but for other configs is OK 👍

**Comment by TomasVotruba** [comment]
Could you always provide minimal YAML snippets that fail and the error? Thanks

**Comment by TomasVotruba** [comment]
Better in new issues, as this is related to extensions.
