### ISSUE TITLE
provide tool(s) as a phar

### ISSUE THREAD

**Issue by clxmstaab** [migrify/migrify#122]
it would be great if this tool (and/or the subtree-splitted reposes) were available as phar files.

in my case they conflict with already present dependencies and installation via composer is not possible.

**Comment by TomasVotruba** [comment]
Hi, agreed.
I'm open to such PR!

I made similar work for package in Symplify
https://github.com/symplify/symplify/commit/e265166fd29f4845524c0cb8b315a82f8fe754b4#diff-661ff08ca26247342b832e9c829edce8

**Comment by szepeviktor** [comment]
Phive PHAR-s! :)

**Comment by TomasVotruba** [comment]
Closing as accepted.  Feel free to send PR :+1:
