### ISSUE TITLE
DX: finding the sources of the repo splitted subprojects

### ISSUE THREAD

**Issue by clxmstaab** [migrify/migrify#123]
it would be great when the repo splitted projects would somehow link to this monorepo to ease contribution.

see e.g. https://github.com/migrify/vendor-patches

this has a great readme which describes how to use the composer package.
- but it does not mention how I could contribute to the actual project
- also its not easy to find the 'issues'-tracker for a substree split

**Comment by TomasVotruba** [comment]
I see. How would it look like?

Could you make small PR for one package?

**Comment by clxmstaab** [comment]
see https://github.com/migrify/migrify/pull/124 for an example

**Comment by TomasVotruba** [comment]
Is this still relevant?

**Comment by TomasVotruba** [comment]
Lazy people tip: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by clxmstaab** [comment]
thx for the tip. I am aware of it.

at the time I created the PR I did not think it would contain the fixes for all the components.
we added them afterwards, but then I forgot to adjust the keyword.

**Comment by TomasVotruba** [comment]
I see :+1:
