### ISSUE TITLE
Symfony Route Usage does not work correctly with jms/i18n-routing-bundle

### ISSUE THREAD

**Issue by GCth** [migrify/migrify#13]
When using https://github.com/schmittjoh/JMSI18nRoutingBundle the generated routes are prefixed with `en__RG__`, eg. `en__RG__statement_get_pdf` depending on the languages used.
The routes saved to database are original, as in `@Route()`, without prefix - `statement_last_pdf`.
The `show-dead-routes` command lists all the prefixed routes, with all languages, as unused.
```
Dead Routes
===========

 -------------------------------- -------------------------------------------------
  Route Name                       Controller
 -------------------------------- -------------------------------------------------
  en__RG__statement_last_pdf       ...\StatementController::lastStatementPdfAction
  pl__RG__statement_last_pdf       ...\StatementController::lastStatementPdfAction
```

**Comment by TomasVotruba** [comment]
What is expected behavior?

**Comment by GCth** [comment]
Since the goal is to find unused code, I would expect that executing `lastStatementPdfAction` with any language (thus from any language-dependent route) should remove all routes to this action from dead routes list.

**Comment by TomasVotruba** [comment]
Could you give me the full `@Route`?

So basically removing the language from route name?

```bash
Used Routes
===========

 -------------------------------- -------------------------------------------------
  Route Name                       Controller
 -------------------------------- -------------------------------------------------
  statement_last_pdf       ...\StatementController::lastStatementPdfAction
```

```bash
Dead Routes
===========

None
```

**Comment by GCth** [comment]
```php
    /**
     * @Route("/oswiadczenie.pdf", name="statement_last_pdf", defaults={"_format" = "pdf"})
     */
    public function lastStatementPdfAction(): Response
```

Yes, I would expect to have an empty dead route list, whenever anyone visits `/oswiadczenie.pdf` or `/en/oswiadczenie.pdf`, as the underlying controller action is the same.

**Comment by TomasVotruba** [comment]
Looking at package code, any idea where it goes wrong?

**Comment by TomasVotruba** [comment]
I don't see any language in the @Route

**Comment by GCth** [comment]
I believe this is not a trivial issue to fix - JMSI18nRoutingBundle is configured using a list of languages, and dynamically generates new routes with prefixed name and prefixed urls, so you can easily get separate urls for content in different language.

It is possible to achieve the same result using:
```
    /**
     * @Route("/oswiadczenie.pdf", name="statement_last_pdf", defaults={"_format" = "pdf", "_locale" = "pl"})
     * @Route("/en/oswiadczenie.pdf", name="en_statement_last_pdf", defaults={"_format" = "pdf", "_locale" = "en"})
     */
    public function lastStatementPdfAction(): Response
```

I suppose the correct way forward is to actually enumerate the actions that were not called, not the routes that were not matched. Using any of `statement_last_pdf`, `en_statement_last_pdf` should mark the `lastStatementPdfAction` as executed and not show it on the dead routes list.

**Comment by GCth** [comment]
Since the schmittjoh/JMSI18nRoutingBundle is considered [obsolete](https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/242#issuecomment-654724483), I have migrated to a [Symfony way](https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing) of doing i18n routes, but the issue is still present in a different form:

```
Dead Routes
===========

  Route Name                                   Controller
 -------------------------------------------- ------------------------------------------------
  app_news_index.en                            App\Controller\NewsController::indexAction
  app_news_index.pl                            App\Controller\NewsController::indexAction
```

**Comment by TomasVotruba** [comment]
We should cover this first test case, as it's impossible to debug just from few lines of annotations.  

PR with failing test case is needed. Feel free to re-open this issue with one.

Thank you for understanding
