### ISSUE TITLE
[ConfigTransformer] YAML/PHP Import route with type missed

### ISSUE THREAD

**Issue by natepage** [migrify/migrify#132]
Hi there! 👋 

We're using ApiPlatform in our projects, I've tried to migrate all the YAML config to PHP, worked for most of it except for the route import with type.

YAML
```yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /
```

Produced PHP
```php
return static function (RoutingConfigurator $routingConfigurator): void {
    $routingConfigurator
        ->import('.') // Missing type here
        ->prefix('/api');
};
```

Expected PHP
```php
return static function (RoutingConfigurator $routingConfigurator): void {
    $routingConfigurator
        ->import('.', 'api_platform') // Add type as 2nd parameter
        ->prefix('/api');
};
```

Do you think this issue would be an "easy-pick"?

**Comment by TomasVotruba** [comment]
The best way is to add test fixture here as a new:  https://github.com/migrify/migrify/blob/master/packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/

The PHP code that needs to be updated is probably somewhere here:

https://github.com/migrify/migrify/blob/master/packages/config-transformer/packages/format-switcher/src/RoutingCaseConverter/ImportRoutingCaseConverter.php#L42-L61

**Comment by natepage** [comment]
Thanks for the merge! I think we can close this issue now.

The PR covers YAML only, is that an issue? I don't think that defining routes in XML is really common but we never know 😄

**Comment by TomasVotruba** [comment]
It actually covers both ;).

If you migrate XML to PHP, the tool internally takes XML to YAML (mostly 1:1),
then that YAML to PHP (the stuff you've added)

**Comment by TomasVotruba** [comment]
> Thanks for the merge! I think we can close this issue now.

Go for it!

Tip for lazy people: https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=issue%20will%20close.-,Closing%20an%20issue%20in%20the%20same%20repository,merged%20into%20the%20default%20branch.

**Comment by natepage** [comment]
Ok good to know, thank you
