### ISSUE TITLE
EntityManager not autowired for class

### ISSUE THREAD

**Issue by SanderHagen** [migrify/migrify#141]
I attempted to convert all of the .YAML files in a project to .PHP but ran into an issue.

The `BlameableEventsSubscriber` in this package https://github.com/KnpLabs/DoctrineBehaviors expects `Doctrine\ORM\EntityManagerInterface`in the constructor. But somehow it does not appear to be autowired because no service for this interface exists according to the error. The exact errormessage is this: `Cannot autowire service "Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber": argument "$entityManager" of method "__construct()" references interface "Doctrine\ORM\EntityManagerInterface" but no such service exists. Did you create a class that implements this interface?`

When using YAML files, everything works correctly, so I guess something went wrong with converting the files

For info: I used this command `vendor/bin/config-transformer switch-format config -i yaml -o php -s 5.1`

**Comment by TomasVotruba** [comment]
It's hard to guess without code.

Few ideas:

- autowire with alias entity manager interface to entity manager
- clear cache
- check if doctrine config is the same 
- convert everything except doctrine config
- convert everything except services
- concert everything except those 2

**Comment by TomasVotruba** [comment]
Closing as answered
