### ISSUE TITLE
Add PHAR file and a signature to Release Process

### ISSUE THREAD

**Issue by szepeviktor** [migrify/migrify#143]
From #122

Dear @TomasVotruba!

Please upload

1. a PHAR file
1. and its signature to releases as attachments

The singing key has to be published on keyservers once.

This way `phive install migrify/migrify` will simply work.

**Comment by szepeviktor** [comment]
I see! There is no box config to just generate a PHAR file :(

**Comment by szepeviktor** [comment]
https://github.com/humbug/box generates PHAR files automatically.

e.g.
```bash
phive install --force-accept-unsigned humbug/box
tools/box compile --working-dir=packages/class-presence
```

**Comment by szepeviktor** [comment]
Should there be several PHAR-s? One for each package??

**Comment by TomasVotruba** [comment]
> Should there be several PHAR-s? One for each package??

Yes, for each package you need this way :+1: 

migrify/migrify is a monorepo, like symfony/symfony, so you should never use it directly, just particular packages

**Comment by szepeviktor** [comment]
Would you like to upload release attachment manually or in a GitHub Action?

**Comment by TomasVotruba** [comment]
That would be tedious with every tag. This process must be automated

**Comment by TomasVotruba** [comment]
Closing as accepted and only PR is needed. To keep more space for active issues, that need attention to resolve.

Thanks for understanding.

**Comment by szepeviktor** [comment]
Okay.

Here we make a GitHub Action https://github.com/phar-io/phive/issues/278
