### ISSUE TITLE
[config-transformer] Add an option to disable import inlining

### ISSUE THREAD

**Issue by mamazu** [migrify/migrify#178]
## The problem

Currently if you convert this kind of file with the config-transformer
```xml
<container>
    <import src="other.xml" />
</container>
```
it would be expected that the resulting php file would look like this
```php
<?php 
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import('other.xml');
}
```
but instead it dumps the contents of the `other.xml` file into it.

## The suggestion
If I understand the code correctly in the command it basically lets the container parse the file and then gets the result of the parsed tree and dumps that into a file. This means this feature is not really possibile to implement other than with some preprocessing of the file before hand. (eg. removing the imports and then sending off the file to be read by the container).

**Comment by TomasVotruba** [comment]
Hi,

that's very interesting undesired behavior.

Could you send failing test fixture? 

Add before/after code here: https://github.com/migrify/migrify/tree/master/packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture

Then add `other.xml` to new directory `/Source/`:
 `https://github.com/migrify/migrify/tree/master/packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Source/other.xml`

**Comment by mamazu** [comment]
Hm, I did as you said. But now it throws an exception that the resource locator can not find the file to include. 
(I renamed `other.xml` to `imported_file.xml` to be more clear in what it's used for.)

```text
Symfony\Component\Config\Exception\LoaderLoadException: 
The file "imported_file.xml" does not exist (in: "/tmp/_temp_fixture_easy_testing") in imported_file.xml
(which is being imported from "/tmp/_temp_fixture_easy_testing/input_15c6c40cfa2fbb430e6a_no_import_inling.xml").
```

Is there anything else I need to do? 
If I hard-code one of the file names in the temp directory into it then it works (aka. it throws the error that was expected).

**Comment by TomasVotruba** [comment]
Could you send the PR? It would be easier to point the problem in exact line

**Comment by TomasVotruba** [comment]
> If I hard-code one of the file names in the temp directory into it then it works

This might be needed in this case.

**Comment by mamazu** [comment]
PR was created. This would be the low-effort approach to use the already existing files in the directory. I don't know however how those filenames in the temp directory are generated.

**Comment by mamazu** [comment]
If the filename is based on the content of the file then changing the content of the `some.xml` would also break the test for the import file as the imported file is no-longer there.

**Comment by TomasVotruba** [comment]
What if you cope the file first here:

https://github.com/migrify/migrify/blob/31a674ddfa9f3ebed76ddd01a391207a7b49377d/packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/XmlToPhpTest.php#L19

```php
    public function test(SmartFileInfo $fixtureFileInfo): void
    {
        // prepare test file to be imported
        FileSystem::copy(__DIR__ . '/Source/some.xml', sys_get_temp_dir() . '/_temp_fixture_easy_testing/some.xml');

        $this->doTestOutput($fixtureFileInfo, 'xml', 'php');
    }

**Comment by mamazu** [comment]
Sure, I will try that.

**Comment by mamazu** [comment]
It works. Now the test fails with the expected error message.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by mamazu** [comment]
No problem. If you have an idea on how to fix it, I'd be glad to help with that as well.

**Comment by TomasVotruba** [comment]
It's possible that XmlLoader includes this file completely. I'd have to debug it manually, but don't have time now. So rought idea...

Maybe this line should be skipped:

- https://github.com/migrify/migrify/blob/31a674ddfa9f3ebed76ddd01a391207a7b49377d/packages/config-transformer/src/DependencyInjection/Loader/IdAwareXmlFileLoader.php#L75

And somehow the content parsed to get these imports and add them in the end?

**Comment by mamazu** [comment]
One way to make it work is to override the `import` function in the `IdAwareFileLoader` and then just save the list of paths that were tried to import. Something like this.
```php
    public function import($resource, $type = null, $ignoreErrors = false, $sourceResource = null, $exclude = null)
    {
        $this->importStatements[]= $resource;
    }
```

The problem then becomes inserting it into the right place in the document.

**Comment by TomasVotruba** [comment]
I like it :+1: 


I think this is the right place: https://github.com/migrify/migrify/blob/31a674ddfa9f3ebed76ddd01a391207a7b49377d/packages/php-config-printer/src/YamlToPhpConverter.php#L91

```php
$yamlArray = $this->checkerServiceParametersShifter->process($yamlArray);

// ...

if (isset($yamlArray['imports'])) {
    $yamlArray['imports'] = array_merge($yamlArray['imports'], $this->xmlImportCollector->provide());
} else {
    $yamlArray['imports'] = $this->xmlImportCollector->provide();
}

// ...

$return = $this->containerConfiguratorReturnClosureFactory->createFromYamlArray($yamlArray);
```

**Comment by mamazu** [comment]
I mean I would guess this also will affect YML files. But your idea sounds good. I will try that.

**Comment by TomasVotruba** [comment]
> I mean I would guess this also will affect YAML files

It might, we'll see. I have a feeling that was one of different between YML and XML file loaders. 
Also, this tool already converted hundreds of configs, also Symplify, Migrify and Rector's, where YAML imports are often used, but never inlined.

**Comment by mamazu** [comment]
Okay, then I have a question about my merge request. If you have time could you have a look why the autowiring is not working. I have never used it (I usually define the services manually).
