### ISSUE TITLE
[config-transformer] Bug: CLI Routing broken due to %router.request_context.base_url%

### ISSUE THREAD

**Issue by ThomasLandauer** [migrify/migrify#198]
This was in my services.yaml:
```yaml
router.request_context.base_url: ''
```
... and config-transformer changed it to this in my new `services.php`:
```php
$parameters->set('router.request_context.base_url', __DIR__ . '/');
```
Now when I do this in a Symfony CLI command:
```php
$router->generate('Foo');
```
... the route I'm getting is:
```
/home/.../config//foo
```
(with `...` being the path to my project dir)

To get the expected route `/foo`, I need to change the value in `services.php` to
```php
$parameters->set('router.request_context.base_url', '');
```
This is probably what you meant with "1. Absolute Paths over Random Paths" at https://tomasvotruba.com/blog/2020/07/16/10-cool-features-you-get-after-switching-from-yaml-to-php-configs/ - just that it doesn't work as expected in this case ;-)

**Comment by TomasVotruba** [comment]
Hi Thomas,

this is definitely a bug :) Could you send failing test fixture?
Right here: https://github.com/migrify/migrify/tree/master/packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal

**Comment by ThomasLandauer** [comment]
There you go :-)
Don't know if this really works - I just copied https://github.com/migrify/migrify/blob/master/packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/twig_path.yaml and guessed the rest...

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Fixed in https://github.com/migrify/migrify/pull/200/files + tagged
