### ISSUE TITLE
travis-to-github-actions broken in many ways

### ISSUE THREAD

**Issue by glensc** [migrify/migrify#220]
https://github.com/migrify/travis-to-github-actions usage says:

```
vendor/bin/travis-to-github-actions convert .travis-ci.yml
```

so, I did:

1. clone latest tag (because master does not resolve dependencies)

```
$ git clone -b 0.4.2 https://github.com/migrify/travis-to-github-actions
$ cd travis-to-github-actions
$ composer install
$ ln -s $(readlink -f ./bin/travis-to-github-actions) /usr/local/bin/
```

2. run the tool

```
➔ travis-to-github-actions convert .travis.yml


 [OK] File .travis.yml/.github/workflows/code_checks.yaml was created



 [OK] Done


➔
```

it says it created file `.travis.yml/.github/workflows/code_checks.yaml`, but no such file was created (even the command said OK). Do note that path conflicts with the existing Travis file, you can't create objects under filename:

```
➔ touch lol
➔ mkdir -p lol/cat
mkdir: cannot create directory ‘lol’: Not a directory
➔
```

`git status` indicates that file path was created which ought to be file contents:

```
➔ git status
On branch travis
Your branch is up to date with 'origin/travis'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"jobs:\n    default:\n        runs-on: ubuntu-latest\n        steps:\n            -\n                uses: actions/checkout@v2\n            -\n                uses: shivammathur/setup-php@v2.5\n"
```

can't even explain properly with terminal output what went wrong, so here's a screenshot from Finder

![image](https://user-images.githubusercontent.com/199095/100088657-23a64b80-2e59-11eb-95c5-2fb4243c0f14.png)

ps:  the travis config is `.travis.yml` not `.travis-ci.yml`, minor typo in documentation

**Comment by glensc** [comment]
Program usage says it accepts directory as well. that does not work either:

```
➔ travis-to-github-actions convert --help
Description:
  Converts Neon syntax to Yaml

Usage:
  convert <source>

Arguments:
  source                Directory or file to convert

```

```
➔ travis-to-github-actions convert .


 [ERROR] Argument 1 passed to Migrify\TravisToGithubActions\TravisToGithubActionsConverter::ensureInputIsPHPTravis()
         must be of the type array, null given, called in
         /Users/glen/scm/tmp/travis-to-github-actions/src/TravisToGithubActionsConverter.php on line 35
```

ps: another error in documentation, command description is wrong: "Converts Neon syntax to Yaml"

**Comment by TomasVotruba** [comment]
Hi,

this is a very very simple prototype, so many cases yet need to be covered.

What is your `.travis-ci.yml` content?

**Comment by glensc** [comment]
Seems to me that filename and file contents are swapped in the code:

```
cd "jobs:    default:        runs-on: ubuntu-latest        steps:            -                uses: actions/checkout@v2            -                uses: shivammathur"

$ more 'setup-php@v2.5
'
.travis.yml/.github/workflows/code_checks.yaml
setup-php@v2.5\
 (END)
```

**Comment by glensc** [comment]
@TomasVotruba: please actually read info given in issue, there are multiple errors (or lack of error handling in other words) that result this, and run the reproducer.

1. file is `.travis.yml` (already noted above)
2. file content is irrelevant, but here it is: https://github.com/eventum/rpc/blob/v4.4.0/.travis.yml

**Comment by TomasVotruba** [comment]
The issue description is very confusing for me. Too many various sources I don't understand.

> Seems to me that filename and file contents are swapped in the code:

If you can confirm that's the problem, please send fix :+1: 

<br>

Closing as too many various issues at once and discussion is falling apart. Make one problem per issue at a time. Ideally not spamming the @migrify repository, but solving them first.
