### ISSUE TITLE
[vendor-patches] Support composer/installers

### ISSUE THREAD

**Issue by kasperg** [migrify/migrify#31]
Thanks a bunch for sharing `vendor-patches`!

Currently this package is limited to files within the `vendor` folder. However some frameworks rely on packages placed elsewhere. This is especially true for [Drupal which rely on a patch-based workflow](https://www.drupal.org/contribute/development). I think `vendor-patches` could be of great help here.

Placement of Composer packages outside `vendor` is typically handled by the Composer plugin [`composer/installers`](https://github.com/composer/installers).

If `vendor-patches` was also implemented as a Composer plugin instead of a standalone CLI tool it should be able to determine the directory for each package and check for `.old` files there.

The usage about the about the same as [the package would register a command](https://getcomposer.org/doc/articles/plugins.md#command-provider) which would then be invoked through Composer e.g. `composer vendor-packages-generate`.

Would you be open to such a contribution?

**Comment by TomasVotruba** [comment]
I don't use plugins, so I have no idea how it works :D, but your request seems reasonable.

> Would you be open to such a contribution?

Go for it :+1:

**Comment by kasperg** [comment]
Closed in favour of the PR.
