### ISSUE TITLE
[ConfigTransformer] Have you migrated from YAML/XML to PHP? Share your PRs here to celebrate 🎉

### ISSUE THREAD

**Issue by TomasVotruba** [migrify/migrify#61]
...and to learn from others 🎓

- https://github.com/symplify/symplify/pull/1997
- https://github.com/symplify/symplify/pull/2005
- https://github.com/symplify/symplify/pull/2007

**Comment by TomasVotruba** [comment]
- https://github.com/symplify/symplify/pull/2009 - 7 files

**Comment by TomasVotruba** [comment]
The biggest change so far:

- https://github.com/eonx-com/easy-monorepo/pull/296/files

**Comment by jordisala1991** [comment]
https://github.com/Runroom/runroom-packages/pull/70

It works really great out of the box, only had a little trouble with inline services.
Because on 4.4 there is no calls on inline services for php (but there are for yaml), and the factory config gave me an error:

**Comment by TomasVotruba** [comment]
Thanks for feedback!

Could you make an issue with minimal input causing the issue and expected output? We have to cover it

**Comment by TomasVotruba** [comment]
Closing as on the menu on Symfony 5.2 releas
