### ISSUE TITLE
[vendor-patches] Autoload definition is broken

### ISSUE THREAD

**Issue by ilmiont** [migrify/migrify#85]
The example given at [https://tomasvotruba.com/blog/2020/07/02/how-to-patch-package-in-vendor-yet-allow-its-updates/](https://tomasvotruba.com/blog/2020/07/02/how-to-patch-package-in-vendor-yet-allow-its-updates/) does not work:

`vendor/bin/vendor-patches generate`

Results in:

`Fatal error: Uncaught Error: Class 'Migrify\VendorPatches\HttpKernel\VendorPatchesKernel' not found in /app/vendor/migrify/vendor-patches/bin/vendor-patches on line 23`

The problem is in `bin/vendor-patches`, with this:

```php
$possibleAutoloadPaths = [
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];
```

But when installed by Composer, `vendor/bin/vendor-patches` is symlinked to `vendor/migrify/vendor-patches/bin/vendor-patches`, so those paths are wrong.

I fixed it with a hack by using `require_once(getcwd() . "/vendor/autoload.php")` at the top of the file.

**Comment by TomasVotruba** [comment]
Could you update add the path that works for you? 

https://github.com/migrify/migrify/blob/be6419113f7161d5ad6e812fc22e7513db1aa9cc/packages/vendor-patches/bin/vendor-patches#L7-L11

**Comment by TomasVotruba** [comment]
Solved by https://github.com/migrify/migrify/pull/89
