### ISSUE TITLE
[vendor-patches] Dependency on sebastian/diff is not declared

### ISSUE THREAD

**Issue by ilmiont** [migrify/migrify#86]
I had to manually `composer require --dev sebastian/diff` to get this working.

**Comment by TomasVotruba** [comment]
Could you add it to `composer.json`?

**Comment by TomasVotruba** [comment]
Solved by https://github.com/migrify/migrify/pull/90

Thanks you!

<br>

Tip for [automated closing](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#:~:text=issue%20will%20close.-,Closing%20an%20issue%20in%20the%20same%20repository,merged%20into%20the%20default%20branch.)
