### ISSUE TITLE
[YAML to PHP migration] Migration of private service config

### ISSUE THREAD

**Issue by TavoNiievez** [migrify/migrify#91]
given the following config in `'services.yaml'`:
```
services:
    _defaults:
        public: false
```
running `vendor/bin/config-transformer switch-format config/services.yaml --intput-format yaml --output-format php --target-symfony-version 5.1` results in:
```
    $services->defaults()
        ->public(false)
```
but the expected behavior is:
```
    $services->defaults()
        ->private()
```

**Comment by TomasVotruba** [comment]
Good point

**Comment by TomasVotruba** [comment]
The line can even be removed, as it is the default behavior

**Comment by TomasVotruba** [comment]
So it seems it for `public(false)` should remain till Symfony 3.3: https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default
