### ISSUE TITLE
[YAML to PHP Migration] Nested calls to set() function when defining parameters

### ISSUE THREAD

**Issue by TavoNiievez** [migrify/migrify#95]
Instead of:
```
    $parameters = $containerConfigurator->parameters();

    $parameters->set('app_locales', 'es');

    $parameters->set('locale', 'es');

    $parameters->set('router.request_context.scheme', '%env(SECURE_SCHEME)%');

```
`config-transformer` could use nested functions. Results in code easier to read and understand:
```
    $containerConfigurator->parameters()
        ->set('app_locales', 'es')
        ->set('locale', 'es')
        ->set('router.request_context.host', '%env(HOST)%');
```
No need to declare:

`$parameters = $containerConfigurator->parameters();`

since the declaration of parameters *is expected* to be done only once, at the top of the services config function

**Comment by TomasVotruba** [comment]
I don't understand this issue. What exact change do you propose? Before/after on one code snippet would help.

**Comment by TavoNiievez** [comment]
What do you think now? (I'm sorry that reading me is such a confusing experience 😆, I hope I'm helping.)

**Comment by TomasVotruba** [comment]
Ah, it makes sense now. I'm just used to code, that transforming words to code is very hard and unrealiable for me :D

For me the best examples are minimal count of lines possible to spot the different. Ideally with diff syntax. E.g.

```diff
-$parameters = $containerConfigurator->parameters();
+$parameters = $containerConfigurator->parameters()
-$parameters->set('key', 'value');
+    ->set('key', 'value');
```

**Comment by TavoNiievez** [comment]
I will keep this in mind in future occasions, thank you very much for your patience.

**Comment by TomasVotruba** [comment]
Thanks!

Would you like to try to implement it?

**Comment by TomasVotruba** [comment]
I'm just looking into config file with like 5 parameters:

![image](https://user-images.githubusercontent.com/924196/87849338-1ea02100-c8e8-11ea-8c51-8a8940cf59f5.png)

The functoin `set()` has only 2 arguments and cannot be extended.
But each `set()` doesn't relate to any other `set()`. It is standalone indepdent call.

Grouping them together with one fluent train will create false impression, they have meaning only together, as service configuration fluent train has.

So on the second look, keeping them separated will make clear that they don't wire together.

**Comment by TomasVotruba** [comment]
:+1: 

Rest of the issues are fixed. It's ready for more battle testing :muscle: :pray:
